project:
  type: website
  output-dir: docs

website:
  title: "My Views"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Fahadbinhashim2005
      - icon: twitter
        href: https://twitter.com
format:
  html: 
    theme: sketchy
    css: styles.css



